name: Build & Deploy

permissions:
  id-token: write

on:
  push:
    branches: [ "main" ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test
      working-directory: ./lambda
  deploy:
    needs: test
    runs-on: ubuntu-latest
    container: ghcr.io/cargo-lambda/cargo-lambda
    environment: prod
    steps:
    - uses: actions/checkout@v6
    - name: Cache dependencies
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          lambda/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      run: bun ci
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@main
      with:
        role-to-assume: arn:aws:iam::267253737119:role/GitHub_PNWFRC-Live_ProdDeployRole
        aws-region: 'us-west-2'
    - name: Setup Node.js environment
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - name: Deploy cdk
      run: bun run cdk deploy --require-approval never --all
